name: Embedded CI Pipeline

on: [push, pull_request] # Tự động chạy khi bạn push code lên

jobs:
  build-and-test:
    runs-on: ubuntu-latest # Mượn máy ảo Linux của GitHub

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Arduino CLI
      run: |
        curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
        arduino-cli core update-index
        arduino-cli core install arduino:avr

    - name: Run Python Automation Script
      run: python scripts/build_check.py
