name: Embedded CI Pipeline

on:
  push:
    branches: [ "github" ]
  pull_request:
    branches: [ "github" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Arduino CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
          sudo mv bin/arduino-cli /usr/local/bin/
          arduino-cli core update-index
          arduino-cli core install arduino:avr

      - name: Install Cppcheck
        run: sudo apt-get install -y cppcheck

      - name: Run Static Analysis
        # Thêm --language=c++ để  đọc file .ino
        run: cppcheck --error-exitcode=1 --language=c++ firmware/

      - name: Run Python Automation Script
      
        run: python scripts/build_check.py
